### ISSUE TITLE
Online-Type Feature Suggestion

### ISSUE THREAD

**Issue by dinosaurioh** [fnbrjs/fnbr.js#4]
Add a function to modify user presence

Client.user.setPresence(presencetypedef);

Presence typedefs:

- Online
- Away / Iddle / Inactive
- Offline

This can be useful in cases that multiple bots are added to someone friends list so they aren't always at the top because it can be kinda annoying.

**Comment by ThisNils** [comment]
Small update on your suggestion: I implemented this in fnbr@2.0.0, there is no ETA for v2 yet.

**Comment by ThisNils** [comment]
Added in version 2.0.0
[Client#setStatus()](https://fnbr.js.org/#/docs/main/2.0.0/class/Client?scrollTo=setStatus)
