### ISSUE TITLE
STW Feature Suggestion

### ISSUE THREAD

**Issue by Im2rnado** [fnbrjs/fnbr.js#5]
STW Shop
 • Rotational Event Store
 • Special Event Store 

STW Daily Rewards List
 • Info about rewards on each specific day

**Comment by Im2rnado** [comment]
https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/storefront/v2/catalog 

Rotational Event Store - response.storefronts[8] 

Special Event Store - response.storefronts[13]
g

**Comment by Im2rnado** [comment]
https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/storefront/v2/catalog 

Rotational Event Store - response.storefronts[8] 

Special Event Store - response.storefronts[13]

**Comment by ThisNils** [comment]
Added in version 2.0.0
[Client#getStorefronts()](https://fnbr.js.org/#/docs/main/2.0.0/class/Client?scrollTo=getStorefronts)
