### ISSUE TITLE
Party Playlists

### ISSUE THREAD

**Issue by OGMatrix** [fnbrjs/fnbr.js#737]
Im trying to set a party playlist but nothing was set. I dont know how to fix but if you have questions please ask.

**Comment by tnfAngel** [comment]
Hello, i will made a PR fixing this.

**Comment by OGMatrix** [comment]
> Hello, I will make a PR to solve this problem.

Nice! 
Thank you!

**Comment by ThisNils** [comment]
The fix will be released as version 4.0.0 soon!

**Comment by OGMatrix** [comment]
> The fix will be released as version 4.0.0 soon!

When will it be released?

**Comment by ThisNils** [comment]
I can't give you a specific date, maybe a few days, maybe 1-2 weeks
