### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by Drizz1le** [fnbrjs/fnbr.js#741]
Hey, can you publish the set Outfit command fix to the npmjs.com website?

**Comment by tnfAngel** [comment]
You can use "fnbr": "github:fnbrjs/fnbr.js#main" on your package.json to install the latest version of fnbr

**Comment by ThisNils** [comment]
Version 4.0.0 will be published on npm soon, including the fix for setOutfit and the outfit getter.

As @tnfAngel said, you can already try the main branch version and adapt your code to the changes, there won't be too many more.
