### ISSUE TITLE
Setoutfit issue

### ISSUE THREAD

**Issue by UnrealSamu** [fnbrjs/fnbr.js#744]
Hi, I was trying to change outfit to the bot but it dont work
![image](https://github.com/fnbrjs/fnbr.js/assets/65288442/7ffb1bb5-6652-4254-88e6-58ce010bfbc1)

**Comment by UnrealSamu** [comment]
Is it possible to send gifts to a friend? (obviously if the account has vbucks)

**Comment by ThisNils** [comment]
Technically yes, but the library doesn't support it (and never will).

FNBR.js is meant for bots, not actual user accounts.
