### ISSUE TITLE
Be able to change multiple cosmetics at the same time

### ISSUE THREAD

**Issue by Mrgaton** [fnbrjs/fnbr.js#793]
Multi-Cosmetic Change Feature

Currently, we can only change one cosmetic item at a time, which can be time-consuming, especially when attempting to customize their entire look. This feature request proposes adding the ability to select and change multiple cosmetic items simultaneously with a single request, streamlining the user experience and enhancing convenience.

Supported cosmetics
- emotes
- outfits
- backpacks
- shoes
- banner
- pet?
- variants

Setting multiple cosmetics at the same time
```js
await party.me.setCosmetics({ emote: {id: '', path: '' }, outfit: {id: '', path: '', variants: ..., enlightment: ...} })
```

Removing multiple cosmetics
```js
await party.me.setCosmetics({ emote: null, outfit: null })
```

If you specify undefined (or nothing), It won't change that cosmetic

```js
await party.me.setCosmetics({ emote: {id: '', path: ''}, outfit: undefined })
```

It would be interesting if they didn't call the underlying .setX implementation, but instead made it bulk.

We could make the .setX methods call .setCosmetics with their correct parameters

Example:
```js
// The method .setOutfit would call:

this.setCosmetic({ outfit: {...} })
```

**Comment by tnfAngel** [comment]
I did it, however neither emotes nor banners are supported (they are not the same meta key), so they can't be changed on the same request. Pets are backpacks with different paths. Variants and enligthment are included on supported cosmetics

**Comment by tnfAngel** [comment]
On request, it no longer distinguishes between undefined and null, so now setting nothing would be ignoring and setting undefined or some falsy value will clear (if clear is supported, otherwise it is simply ignored)
